name: Notify via Telegram

on:
  push:
    branches:
      - main        # run on pushes to main
  schedule:
     -cron: "0 */2 * * *"   # every 4 hours
  workflow_dispatch:        # manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: cache/
          key: news-cache

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm start
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          URL: ${{ secrets.URL }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
